version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.54.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Build executable
          command: cargo build --release
      - run:
          name: Run the built executable
          command: ./target/release/rust-circle


workflows:
  build-and-run:
    jobs:
      - build
